export default FETCH_ARTIST = "app/FETCH_ARTIST";
export default FETCH_ARTIST_SUCCESS = "app/FETCH_ARTIST_SUCCESS";
export default FETCH_ARTIST_EVENTS = "app/FETCH_ARTIST_EVENTS";
export default FETCH_ARTIST_EVENTS_SUCCESS = "app/FETCH_ARTIST_EVENTS_SUCCESS";
export default THROW_API_ERROR = "app/THROW_API_ERROR";
